### ISSUE TITLE
Figure out how to determine whether you are the host of a raid or not

### ISSUE THREAD

**Issue by tommoyang** [tommoyang/Mahira#18]
Used for quest.js line 627

**Comment by tommoyang** [comment]
Related to #13

**Comment by Mattish** [comment]
[raid_2017_12_10.json.txt](https://github.com/tommoyang/Mahira/files/1545829/raid_2017_12_10.json.txt)
[solo_2017_12_10.json.txt](https://github.com/tommoyang/Mahira/files/1545830/solo_2017_12_10.json.txt)

Example json in 'StartBattle' function.

Raid json has a `chat` field and `is_host` field.
Solo json does not have `chat` or `is_host` field.

**Comment by Mattish** [comment]
If you are running multiple raids at once, could consider holding a map of `raid_id` to hold this start information.

There is a `timer` field also, so you could expire entries in the map if don't get an associated 'battle finished' message or miss it
