### ISSUE TITLE
Why is there a callback passed to GetAP

### ISSUE THREAD

**Issue by tommoyang** [tommoyang/Mahira#19]
quest.js line 463

**Comment by Mattish** [comment]
Thought it didn't look to be doing much but I'll double check what it's doing. Appears to be setting some image to clickable in the devtools ui at first glance

**Comment by Mattish** [comment]
Those images have been commented out in the html for over 10 months with no other thing using the public GetAP method, nuking it.

**Comment by Mattish** [comment]
so the APBP.GetAP is actually more a "subscribe to AP updates", but its only use for this feature.

The only thing its actually updating is this set 'events' array, but its only ever populated with:
`events.push(createEvent('#event/teamraid024'));`

The only thing it all amounts to is updating '#event-item-' and '#event-image' in the UI to be able to click them. But they are commented out in the UI(for 10 months now), so its an unfinished and its getting the 💣

**Comment by Mattish** [comment]
#20

**Comment by Mattish** [comment]
Will close and merge #20 once #17 has been merged due to quests.js changes
